/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Customer Relationship Management Outbound API
 * APIs to cater for Customer Relationship Management external (outbound) functionality with OPERA. These APIs facilitate various operations related to getting data from an external system, and inserting it into OPERA.<br /><br /> Compatible with OPERA Cloud release 22.3.0.0.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2022 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 22.3.0.0
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceLink } from './InstanceLink';
import {
    InstanceLinkFromJSON,
    InstanceLinkFromJSONTyped,
    InstanceLinkToJSON,
} from './InstanceLink';
import type { MemberPointToExpireType } from './MemberPointToExpireType';
import {
    MemberPointToExpireTypeFromJSON,
    MemberPointToExpireTypeFromJSONTyped,
    MemberPointToExpireTypeToJSON,
} from './MemberPointToExpireType';

/**
 * Response object for fetching member points to expire information.
 * @export
 * @interface MemberPointsToExpire
 */
export interface MemberPointsToExpire {
    /**
     * List of of member points to expire.
     * @type {Array<MemberPointToExpireType>}
     * @memberof MemberPointsToExpire
     */
    memberPointsToExpireList?: Array<MemberPointToExpireType>;
    /**
     * 
     * @type {Array<InstanceLink>}
     * @memberof MemberPointsToExpire
     */
    links?: Array<InstanceLink>;
}

/**
 * Check if a given object implements the MemberPointsToExpire interface.
 */
export function instanceOfMemberPointsToExpire(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MemberPointsToExpireFromJSON(json: any): MemberPointsToExpire {
    return MemberPointsToExpireFromJSONTyped(json, false);
}

export function MemberPointsToExpireFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberPointsToExpire {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'memberPointsToExpireList': !exists(json, 'memberPointsToExpireList') ? undefined : ((json['memberPointsToExpireList'] as Array<any>).map(MemberPointToExpireTypeFromJSON)),
        'links': !exists(json, 'links') ? undefined : ((json['links'] as Array<any>).map(InstanceLinkFromJSON)),
    };
}

export function MemberPointsToExpireToJSON(value?: MemberPointsToExpire | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'memberPointsToExpireList': value.memberPointsToExpireList === undefined ? undefined : ((value.memberPointsToExpireList as Array<any>).map(MemberPointToExpireTypeToJSON)),
        'links': value.links === undefined ? undefined : ((value.links as Array<any>).map(InstanceLinkToJSON)),
    };
}

