/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Front Desk Configuration API
 * APIs to cater for Front Desk Configuration in OPERA Cloud. Here you can find operations to get, post, put and delete front desk codes such as commission codes, transaction groups, codes & subgroups, articles, payment methods and credit card types.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CateringInfoType } from './CateringInfoType';
import {
    CateringInfoTypeFromJSON,
    CateringInfoTypeFromJSONTyped,
    CateringInfoTypeToJSON,
} from './CateringInfoType';
import type { CateringVarianceInfoType } from './CateringVarianceInfoType';
import {
    CateringVarianceInfoTypeFromJSON,
    CateringVarianceInfoTypeFromJSONTyped,
    CateringVarianceInfoTypeToJSON,
} from './CateringVarianceInfoType';

/**
 * Budget Forecast information for Catering segment code.
 * @export
 * @interface CateringCodeInformationType
 */
export interface CateringCodeInformationType {
    /**
     * 
     * @type {CateringVarianceInfoType}
     * @memberof CateringCodeInformationType
     */
    aBVarianceInfo?: CateringVarianceInfoType;
    /**
     * 
     * @type {CateringVarianceInfoType}
     * @memberof CateringCodeInformationType
     */
    aFVarianceInfo?: CateringVarianceInfoType;
    /**
     * 
     * @type {CateringInfoType}
     * @memberof CateringCodeInformationType
     */
    actualInfo?: CateringInfoType;
    /**
     * 
     * @type {CateringInfoType}
     * @memberof CateringCodeInformationType
     */
    budgetInfo?: CateringInfoType;
    /**
     * Catering segment code for which budget forecast information is fetched.
     * @type {string}
     * @memberof CateringCodeInformationType
     */
    cateringCode?: string;
    /**
     * Catering code description for segment code.
     * @type {string}
     * @memberof CateringCodeInformationType
     */
    cateringCodeDescription?: string;
    /**
     * Catering code group of segment code.
     * @type {string}
     * @memberof CateringCodeInformationType
     */
    cateringCodeGrp?: string;
    /**
     * 
     * @type {CateringVarianceInfoType}
     * @memberof CateringCodeInformationType
     */
    fBVarianceInfo?: CateringVarianceInfoType;
    /**
     * 
     * @type {CateringInfoType}
     * @memberof CateringCodeInformationType
     */
    forecastInfo?: CateringInfoType;
}

/**
 * Check if a given object implements the CateringCodeInformationType interface.
 */
export function instanceOfCateringCodeInformationType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CateringCodeInformationTypeFromJSON(json: any): CateringCodeInformationType {
    return CateringCodeInformationTypeFromJSONTyped(json, false);
}

export function CateringCodeInformationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CateringCodeInformationType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aBVarianceInfo': !exists(json, 'aBVarianceInfo') ? undefined : CateringVarianceInfoTypeFromJSON(json['aBVarianceInfo']),
        'aFVarianceInfo': !exists(json, 'aFVarianceInfo') ? undefined : CateringVarianceInfoTypeFromJSON(json['aFVarianceInfo']),
        'actualInfo': !exists(json, 'actualInfo') ? undefined : CateringInfoTypeFromJSON(json['actualInfo']),
        'budgetInfo': !exists(json, 'budgetInfo') ? undefined : CateringInfoTypeFromJSON(json['budgetInfo']),
        'cateringCode': !exists(json, 'cateringCode') ? undefined : json['cateringCode'],
        'cateringCodeDescription': !exists(json, 'cateringCodeDescription') ? undefined : json['cateringCodeDescription'],
        'cateringCodeGrp': !exists(json, 'cateringCodeGrp') ? undefined : json['cateringCodeGrp'],
        'fBVarianceInfo': !exists(json, 'fBVarianceInfo') ? undefined : CateringVarianceInfoTypeFromJSON(json['fBVarianceInfo']),
        'forecastInfo': !exists(json, 'forecastInfo') ? undefined : CateringInfoTypeFromJSON(json['forecastInfo']),
    };
}

export function CateringCodeInformationTypeToJSON(value?: CateringCodeInformationType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aBVarianceInfo': CateringVarianceInfoTypeToJSON(value.aBVarianceInfo),
        'aFVarianceInfo': CateringVarianceInfoTypeToJSON(value.aFVarianceInfo),
        'actualInfo': CateringInfoTypeToJSON(value.actualInfo),
        'budgetInfo': CateringInfoTypeToJSON(value.budgetInfo),
        'cateringCode': value.cateringCode,
        'cateringCodeDescription': value.cateringCodeDescription,
        'cateringCodeGrp': value.cateringCodeGrp,
        'fBVarianceInfo': CateringVarianceInfoTypeToJSON(value.fBVarianceInfo),
        'forecastInfo': CateringInfoTypeToJSON(value.forecastInfo),
    };
}

