/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Front Desk Operations Service
 * APIs to cater for Front Desk Operations and Front Desk Statistic functionality in OPERA Cloud. <br /><br /> Front Desk features some of the most commonly used operations in OPERA Cloud, such as managing guest arrivals, managing in-house guests, and managing guest departures. Some additional tasks you can complete from the Front Desk menu are room searches, room assignments, and quick check outs as well as opening folios, creating registration cards, setting wake up calls, and sending messages to guests.<br /><br /> Compatible with OPERA Cloud release 24.4.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2024 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 24.4
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TimeSpanType } from './TimeSpanType';
import {
    TimeSpanTypeFromJSON,
    TimeSpanTypeFromJSONTyped,
    TimeSpanTypeToJSON,
} from './TimeSpanType';
import type { WakeUpCallResvInfoType } from './WakeUpCallResvInfoType';
import {
    WakeUpCallResvInfoTypeFromJSON,
    WakeUpCallResvInfoTypeFromJSONTyped,
    WakeUpCallResvInfoTypeToJSON,
} from './WakeUpCallResvInfoType';
import type { WakeUpCallStatusType } from './WakeUpCallStatusType';
import {
    WakeUpCallStatusTypeFromJSON,
    WakeUpCallStatusTypeFromJSONTyped,
    WakeUpCallStatusTypeToJSON,
} from './WakeUpCallStatusType';

/**
 * Criteria to search and retrieve wake up calls.
 * @export
 * @interface WakeUpCallType
 */
export interface WakeUpCallType {
    /**
     * 
     * @type {WakeUpCallResvInfoType}
     * @memberof WakeUpCallType
     */
    reservationInfo?: WakeUpCallResvInfoType;
    /**
     * Time on which wake up call is set.
     * @type {string}
     * @memberof WakeUpCallType
     */
    callTime?: string;
    /**
     * Follow up call time.
     * @type {string}
     * @memberof WakeUpCallType
     */
    followUpCallTime?: string;
    /**
     * Is the call type follow up.
     * @type {boolean}
     * @memberof WakeUpCallType
     */
    isFollowUpCall?: boolean;
    /**
     * 
     * @type {WakeUpCallStatusType}
     * @memberof WakeUpCallType
     */
    status?: WakeUpCallStatusType;
    /**
     * Date on which wake up call was processed.
     * @type {string}
     * @memberof WakeUpCallType
     */
    processedDate?: string;
    /**
     * Time on which wake up call was processed.
     * @type {string}
     * @memberof WakeUpCallType
     */
    processedTime?: string;
    /**
     * Special instructions for the wake up call.
     * @type {string}
     * @memberof WakeUpCallType
     */
    instructions?: string;
    /**
     * 
     * @type {TimeSpanType}
     * @memberof WakeUpCallType
     */
    timeSpan?: TimeSpanType;
    /**
     * New Time on which wake up call is set. Used to change the Followup Call time
     * @type {string}
     * @memberof WakeUpCallType
     */
    newCallTime?: string;
    /**
     * New Follow up call time.Used to change the Followup Call time.
     * @type {string}
     * @memberof WakeUpCallType
     */
    newFollowUpCallTime?: string;
    /**
     * Time stamp of the creation.
     * @type {string}
     * @memberof WakeUpCallType
     */
    createDateTime?: string;
    /**
     * ID of creator. The creator could be a software system identifier or an identifier of an employee resposible for the creation.
     * @type {string}
     * @memberof WakeUpCallType
     */
    creatorId?: string;
    /**
     * Time stamp of last modification.
     * @type {string}
     * @memberof WakeUpCallType
     */
    lastModifyDateTime?: string;
    /**
     * Identifies the last software system or person to modify a record.
     * @type {string}
     * @memberof WakeUpCallType
     */
    lastModifierId?: string;
    /**
     * Date an item will be purged from a database (e.g., from a live database to an archive).
     * @type {string}
     * @memberof WakeUpCallType
     */
    purgeDate?: string;
}

/**
 * Check if a given object implements the WakeUpCallType interface.
 */
export function instanceOfWakeUpCallType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WakeUpCallTypeFromJSON(json: any): WakeUpCallType {
    return WakeUpCallTypeFromJSONTyped(json, false);
}

export function WakeUpCallTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WakeUpCallType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reservationInfo': !exists(json, 'reservationInfo') ? undefined : WakeUpCallResvInfoTypeFromJSON(json['reservationInfo']),
        'callTime': !exists(json, 'callTime') ? undefined : json['callTime'],
        'followUpCallTime': !exists(json, 'followUpCallTime') ? undefined : json['followUpCallTime'],
        'isFollowUpCall': !exists(json, 'isFollowUpCall') ? undefined : json['isFollowUpCall'],
        'status': !exists(json, 'status') ? undefined : WakeUpCallStatusTypeFromJSON(json['status']),
        'processedDate': !exists(json, 'processedDate') ? undefined : json['processedDate'],
        'processedTime': !exists(json, 'processedTime') ? undefined : json['processedTime'],
        'instructions': !exists(json, 'instructions') ? undefined : json['instructions'],
        'timeSpan': !exists(json, 'timeSpan') ? undefined : TimeSpanTypeFromJSON(json['timeSpan']),
        'newCallTime': !exists(json, 'newCallTime') ? undefined : json['newCallTime'],
        'newFollowUpCallTime': !exists(json, 'newFollowUpCallTime') ? undefined : json['newFollowUpCallTime'],
        'createDateTime': !exists(json, 'createDateTime') ? undefined : json['createDateTime'],
        'creatorId': !exists(json, 'creatorId') ? undefined : json['creatorId'],
        'lastModifyDateTime': !exists(json, 'lastModifyDateTime') ? undefined : json['lastModifyDateTime'],
        'lastModifierId': !exists(json, 'lastModifierId') ? undefined : json['lastModifierId'],
        'purgeDate': !exists(json, 'purgeDate') ? undefined : json['purgeDate'],
    };
}

export function WakeUpCallTypeToJSON(value?: WakeUpCallType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reservationInfo': WakeUpCallResvInfoTypeToJSON(value.reservationInfo),
        'callTime': value.callTime,
        'followUpCallTime': value.followUpCallTime,
        'isFollowUpCall': value.isFollowUpCall,
        'status': WakeUpCallStatusTypeToJSON(value.status),
        'processedDate': value.processedDate,
        'processedTime': value.processedTime,
        'instructions': value.instructions,
        'timeSpan': TimeSpanTypeToJSON(value.timeSpan),
        'newCallTime': value.newCallTime,
        'newFollowUpCallTime': value.newFollowUpCallTime,
        'createDateTime': value.createDateTime,
        'creatorId': value.creatorId,
        'lastModifyDateTime': value.lastModifyDateTime,
        'lastModifierId': value.lastModifierId,
        'purgeDate': value.purgeDate,
    };
}

