/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud API for Customer Management Service
 * This API deals with the different aspect of the CustomerManagement.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AttachmentType } from './AttachmentType';
import {
    AttachmentTypeFromJSON,
    AttachmentTypeFromJSONTyped,
    AttachmentTypeToJSON,
} from './AttachmentType';

/**
 * Attachment List.
 * @export
 * @interface AttachmentsType
 */
export interface AttachmentsType extends Array<AttachmentType> {
}

/**
 * Check if a given object implements the AttachmentsType interface.
 */
export function instanceOfAttachmentsType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AttachmentsTypeFromJSON(json: any): AttachmentsType {
    return AttachmentsTypeFromJSONTyped(json, false);
}

export function AttachmentsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentsType {
    return json;
}

export function AttachmentsTypeToJSON(value?: AttachmentsType | null): any {
    return value;
}

