/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud API for Customer Management Service
 * This API deals with the different aspect of the CustomerManagement.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { TrackItItemsType } from './TrackItItemsType';
import {
    TrackItItemsTypeFromJSON,
    TrackItItemsTypeFromJSONTyped,
    TrackItItemsTypeToJSON,
} from './TrackItItemsType';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * Response object that retrieves Track It items.
 * @export
 * @interface TrackItItems
 */
export interface TrackItItems {
    /**
     * Used for codes in the OPERA Code tables. Possible values of this pattern are 1, 101, 101.EQP, or 101.EQP.X.
     * @type {string}
     * @memberof TrackItItems
     */
    hotelId?: string;
    /**
     * 
     * @type {Links}
     * @memberof TrackItItems
     */
    links?: Links;
    /**
     * 
     * @type {TrackItItemsType}
     * @memberof TrackItItems
     */
    trackItItemsInfo?: TrackItItemsType;
    /**
     * 
     * @type {WarningsType}
     * @memberof TrackItItems
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the TrackItItems interface.
 */
export function instanceOfTrackItItems(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrackItItemsFromJSON(json: any): TrackItItems {
    return TrackItItemsFromJSONTyped(json, false);
}

export function TrackItItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackItItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hotelId': !exists(json, 'hotelId') ? undefined : json['hotelId'],
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'trackItItemsInfo': !exists(json, 'trackItItemsInfo') ? undefined : TrackItItemsTypeFromJSON(json['trackItItemsInfo']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function TrackItItemsToJSON(value?: TrackItItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hotelId': value.hotelId,
        'links': LinksToJSON(value.links),
        'trackItItemsInfo': TrackItItemsTypeToJSON(value.trackItItemsInfo),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

