/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Customer Relationship Management API
 * APIs to cater for Customer Relationship Management (profile) functionality in OPERA Cloud.  There are different types of profiles in OPERA Cloud, including Guest, Company, Travel Agent, Source, Group, and Contact profile types.  A profile can store and display a wide range of information about the guest, company, travel agent etc., depending upon the type of profile.  For example, a guest profile can store the guest name, address, contact information, details on billing, membership benefits, preferences and much more.  All profiles in OPERA when created are assigned a ProfileID.  This ID will be used throughout the CRM APIs.<br /><br /> Compatible with OPERA Cloud release 24.4.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2024 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 24.4
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MembershipAwardBasedOnType } from './MembershipAwardBasedOnType';
import {
    MembershipAwardBasedOnTypeFromJSON,
    MembershipAwardBasedOnTypeFromJSONTyped,
    MembershipAwardBasedOnTypeToJSON,
} from './MembershipAwardBasedOnType';

/**
 * Information related to Member Award Issue List.
 * @export
 * @interface MembershipAwardListType
 */
export interface MembershipAwardListType {
    /**
     * Card number of the membership.
     * @type {number}
     * @memberof MembershipAwardListType
     */
    membershipId?: number;
    /**
     * Membership type for which awards are defined.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    membershipType?: string;
    /**
     * Level of this Membership Type.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    membershipLevel?: string;
    /**
     * Name to be displayed on the membership card.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    nameOnCard?: string;
    /**
     * Joined date on the Card.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    joinDate?: string;
    /**
     * Expiry date on the Card.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    expireDate?: string;
    /**
     * Indicates Membership Card Number.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    membershipCardNo?: string;
    /**
     * Total award points available for redemption.
     * @type {number}
     * @memberof MembershipAwardListType
     */
    totalAvailablePoints?: number;
    /**
     * Property at which the award was issued.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    hotelId?: string;
    /**
     * An identifying number of the award, assigned by the system when the award was issued.
     * @type {number}
     * @memberof MembershipAwardListType
     */
    awardNumber?: number;
    /**
     * Number of points required by the award.
     * @type {number}
     * @memberof MembershipAwardListType
     */
    awardPoints?: number;
    /**
     * Indicates member is below the threshold limit or not to request award.
     * @type {number}
     * @memberof MembershipAwardListType
     */
    thresholdPoints?: number;
    /**
     * Code assigned to this membership award.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    awardCode?: string;
    /**
     * The cancel days, set up in awards configuration that establishes the number of days before arrival when a reservation may be cancelled without an award points penalty.
     * @type {number}
     * @memberof MembershipAwardListType
     */
    cancelDays?: number;
    /**
     * Date when the award was issued
     * @type {string}
     * @memberof MembershipAwardListType
     */
    dateAwarded?: string;
    /**
     * Reservation confirmation number.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    bookingNumber?: string;
    /**
     * Property Reservation number.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    hotelBookingNumber?: string;
    /**
     * The arrival date of the stay for when the award is associated.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    arrivalDate?: string;
    /**
     * The award points that will be deducted (based on a cancel days restriction) if the award is cancelled. (Cancel days, set up in awards configuration, and establish the number of days before arrival when a reservation may be cancelled without an award points penalty.)
     * @type {number}
     * @memberof MembershipAwardListType
     */
    cancelPenaltyPoints?: number;
    /**
     * If the award was cancelled, the system-generated award cancellation number appears here.
     * @type {number}
     * @memberof MembershipAwardListType
     */
    awardCancellationNumber?: number;
    /**
     * If the reservation associated with the award was cancelled, the reservation cancellation date appears here.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    awardCancelDate?: string;
    /**
     * The number of points actually deducted from the member's total award points if there is a penalty points restriction associated with the award cancellation.
     * @type {number}
     * @memberof MembershipAwardListType
     */
    actualCancelPoints?: number;
    /**
     * If the reservation associated with the award was cancelled, the reservation cancellation number appears here.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    reservationCancellationNumber?: string;
    /**
     * If this award was included on a statement, the statement ID appears here. The field is blank if the award has not yet been reported on a statement
     * @type {number}
     * @memberof MembershipAwardListType
     */
    statementId?: number;
    /**
     * If this award was included on a statement, the cancel statement ID appears here. The field is blank if the award has not yet been reported on a statement
     * @type {number}
     * @memberof MembershipAwardListType
     */
    cancelStatementID?: number;
    /**
     * If this award was included on a statement, the member statement ID appears here. The field is blank if the award has not yet been reported on a statement
     * @type {number}
     * @memberof MembershipAwardListType
     */
    memberStatementId?: number;
    /**
     * If this award was included on a statement, the cancel member statement ID appears here. The field is blank if the award has not yet been reported on a statement
     * @type {number}
     * @memberof MembershipAwardListType
     */
    cancelMemberStatementID?: number;
    /**
     * Number of nights cancel policy is applicable.
     * @type {number}
     * @memberof MembershipAwardListType
     */
    numberOfNights?: number;
    /**
     * The date of the reservation associated with the award. There may be more than one date (multiple nights) associated with award
     * @type {string}
     * @memberof MembershipAwardListType
     */
    stayDate?: string;
    /**
     * The date of the departure of the reservation associated with the award. There may be more than one date (multiple nights) associated with award
     * @type {string}
     * @memberof MembershipAwardListType
     */
    departureDate?: string;
    /**
     * Type of cancel policy.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    cancelPolicyType?: string;
    /**
     * The source for the reservation associated with the award.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    awardSource?: string;
    /**
     * Total calculated points to cancel an issued award.
     * @type {number}
     * @memberof MembershipAwardListType
     */
    calculatedCancelPoints?: number;
    /**
     * 
     * @type {MembershipAwardBasedOnType}
     * @memberof MembershipAwardListType
     */
    awardBasedOn?: MembershipAwardBasedOnType;
    /**
     * Indicates PMS Reservation Number.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    pmsResvNo?: string;
    /**
     * Indicates CRS Booking Number.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    crsBookNo?: string;
    /**
     * Indicates the Product associated with the award.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    product?: string;
    /**
     * Rate plan code associated with the award.
     * @type {string}
     * @memberof MembershipAwardListType
     */
    ratePlanCode?: string;
}

/**
 * Check if a given object implements the MembershipAwardListType interface.
 */
export function instanceOfMembershipAwardListType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MembershipAwardListTypeFromJSON(json: any): MembershipAwardListType {
    return MembershipAwardListTypeFromJSONTyped(json, false);
}

export function MembershipAwardListTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembershipAwardListType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'membershipId': !exists(json, 'membershipId') ? undefined : json['membershipId'],
        'membershipType': !exists(json, 'membershipType') ? undefined : json['membershipType'],
        'membershipLevel': !exists(json, 'membershipLevel') ? undefined : json['membershipLevel'],
        'nameOnCard': !exists(json, 'nameOnCard') ? undefined : json['nameOnCard'],
        'joinDate': !exists(json, 'joinDate') ? undefined : json['joinDate'],
        'expireDate': !exists(json, 'expireDate') ? undefined : json['expireDate'],
        'membershipCardNo': !exists(json, 'membershipCardNo') ? undefined : json['membershipCardNo'],
        'totalAvailablePoints': !exists(json, 'totalAvailablePoints') ? undefined : json['totalAvailablePoints'],
        'hotelId': !exists(json, 'hotelId') ? undefined : json['hotelId'],
        'awardNumber': !exists(json, 'awardNumber') ? undefined : json['awardNumber'],
        'awardPoints': !exists(json, 'awardPoints') ? undefined : json['awardPoints'],
        'thresholdPoints': !exists(json, 'thresholdPoints') ? undefined : json['thresholdPoints'],
        'awardCode': !exists(json, 'awardCode') ? undefined : json['awardCode'],
        'cancelDays': !exists(json, 'cancelDays') ? undefined : json['cancelDays'],
        'dateAwarded': !exists(json, 'dateAwarded') ? undefined : json['dateAwarded'],
        'bookingNumber': !exists(json, 'bookingNumber') ? undefined : json['bookingNumber'],
        'hotelBookingNumber': !exists(json, 'hotelBookingNumber') ? undefined : json['hotelBookingNumber'],
        'arrivalDate': !exists(json, 'arrivalDate') ? undefined : json['arrivalDate'],
        'cancelPenaltyPoints': !exists(json, 'cancelPenaltyPoints') ? undefined : json['cancelPenaltyPoints'],
        'awardCancellationNumber': !exists(json, 'awardCancellationNumber') ? undefined : json['awardCancellationNumber'],
        'awardCancelDate': !exists(json, 'awardCancelDate') ? undefined : json['awardCancelDate'],
        'actualCancelPoints': !exists(json, 'actualCancelPoints') ? undefined : json['actualCancelPoints'],
        'reservationCancellationNumber': !exists(json, 'reservationCancellationNumber') ? undefined : json['reservationCancellationNumber'],
        'statementId': !exists(json, 'statementId') ? undefined : json['statementId'],
        'cancelStatementID': !exists(json, 'cancelStatementID') ? undefined : json['cancelStatementID'],
        'memberStatementId': !exists(json, 'memberStatementId') ? undefined : json['memberStatementId'],
        'cancelMemberStatementID': !exists(json, 'cancelMemberStatementID') ? undefined : json['cancelMemberStatementID'],
        'numberOfNights': !exists(json, 'numberOfNights') ? undefined : json['numberOfNights'],
        'stayDate': !exists(json, 'stayDate') ? undefined : json['stayDate'],
        'departureDate': !exists(json, 'departureDate') ? undefined : json['departureDate'],
        'cancelPolicyType': !exists(json, 'cancelPolicyType') ? undefined : json['cancelPolicyType'],
        'awardSource': !exists(json, 'awardSource') ? undefined : json['awardSource'],
        'calculatedCancelPoints': !exists(json, 'calculatedCancelPoints') ? undefined : json['calculatedCancelPoints'],
        'awardBasedOn': !exists(json, 'awardBasedOn') ? undefined : MembershipAwardBasedOnTypeFromJSON(json['awardBasedOn']),
        'pmsResvNo': !exists(json, 'pmsResvNo') ? undefined : json['pmsResvNo'],
        'crsBookNo': !exists(json, 'crsBookNo') ? undefined : json['crsBookNo'],
        'product': !exists(json, 'product') ? undefined : json['product'],
        'ratePlanCode': !exists(json, 'ratePlanCode') ? undefined : json['ratePlanCode'],
    };
}

export function MembershipAwardListTypeToJSON(value?: MembershipAwardListType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'membershipId': value.membershipId,
        'membershipType': value.membershipType,
        'membershipLevel': value.membershipLevel,
        'nameOnCard': value.nameOnCard,
        'joinDate': value.joinDate,
        'expireDate': value.expireDate,
        'membershipCardNo': value.membershipCardNo,
        'totalAvailablePoints': value.totalAvailablePoints,
        'hotelId': value.hotelId,
        'awardNumber': value.awardNumber,
        'awardPoints': value.awardPoints,
        'thresholdPoints': value.thresholdPoints,
        'awardCode': value.awardCode,
        'cancelDays': value.cancelDays,
        'dateAwarded': value.dateAwarded,
        'bookingNumber': value.bookingNumber,
        'hotelBookingNumber': value.hotelBookingNumber,
        'arrivalDate': value.arrivalDate,
        'cancelPenaltyPoints': value.cancelPenaltyPoints,
        'awardCancellationNumber': value.awardCancellationNumber,
        'awardCancelDate': value.awardCancelDate,
        'actualCancelPoints': value.actualCancelPoints,
        'reservationCancellationNumber': value.reservationCancellationNumber,
        'statementId': value.statementId,
        'cancelStatementID': value.cancelStatementID,
        'memberStatementId': value.memberStatementId,
        'cancelMemberStatementID': value.cancelMemberStatementID,
        'numberOfNights': value.numberOfNights,
        'stayDate': value.stayDate,
        'departureDate': value.departureDate,
        'cancelPolicyType': value.cancelPolicyType,
        'awardSource': value.awardSource,
        'calculatedCancelPoints': value.calculatedCancelPoints,
        'awardBasedOn': MembershipAwardBasedOnTypeToJSON(value.awardBasedOn),
        'pmsResvNo': value.pmsResvNo,
        'crsBookNo': value.crsBookNo,
        'product': value.product,
        'ratePlanCode': value.ratePlanCode,
    };
}

