/*
OPERA Cloud Reservation Master Data Management API

APIs to cater for Reservation Configuration in OPERA Cloud. In this module you can retrieve, create, modify or delete configuration related to Reservations, Blocks and Leisure Management.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>

API version: 23.2
Contact: hospitality_apis_ww_grp@oracle.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rsvcfg

import (
	"encoding/json"
)

// checks if the PutLocatorCodesTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutLocatorCodesTemplateRequest{}

// PutLocatorCodesTemplateRequest struct for PutLocatorCodesTemplateRequest
type PutLocatorCodesTemplateRequest struct {
	Links *Links `json:"links,omitempty"`
	LocatorCodes *LocatorCodesTemplateType `json:"locatorCodes,omitempty"`
	Warnings *WarningsType `json:"warnings,omitempty"`
}

// NewPutLocatorCodesTemplateRequest instantiates a new PutLocatorCodesTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutLocatorCodesTemplateRequest() *PutLocatorCodesTemplateRequest {
	this := PutLocatorCodesTemplateRequest{}
	return &this
}

// NewPutLocatorCodesTemplateRequestWithDefaults instantiates a new PutLocatorCodesTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutLocatorCodesTemplateRequestWithDefaults() *PutLocatorCodesTemplateRequest {
	this := PutLocatorCodesTemplateRequest{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *PutLocatorCodesTemplateRequest) GetLinks() Links {
	if o == nil || IsNil(o.Links) {
		var ret Links
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutLocatorCodesTemplateRequest) GetLinksOk() (*Links, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *PutLocatorCodesTemplateRequest) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Links and assigns it to the Links field.
func (o *PutLocatorCodesTemplateRequest) SetLinks(v Links) {
	o.Links = &v
}

// GetLocatorCodes returns the LocatorCodes field value if set, zero value otherwise.
func (o *PutLocatorCodesTemplateRequest) GetLocatorCodes() LocatorCodesTemplateType {
	if o == nil || IsNil(o.LocatorCodes) {
		var ret LocatorCodesTemplateType
		return ret
	}
	return *o.LocatorCodes
}

// GetLocatorCodesOk returns a tuple with the LocatorCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutLocatorCodesTemplateRequest) GetLocatorCodesOk() (*LocatorCodesTemplateType, bool) {
	if o == nil || IsNil(o.LocatorCodes) {
		return nil, false
	}
	return o.LocatorCodes, true
}

// HasLocatorCodes returns a boolean if a field has been set.
func (o *PutLocatorCodesTemplateRequest) HasLocatorCodes() bool {
	if o != nil && !IsNil(o.LocatorCodes) {
		return true
	}

	return false
}

// SetLocatorCodes gets a reference to the given LocatorCodesTemplateType and assigns it to the LocatorCodes field.
func (o *PutLocatorCodesTemplateRequest) SetLocatorCodes(v LocatorCodesTemplateType) {
	o.LocatorCodes = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *PutLocatorCodesTemplateRequest) GetWarnings() WarningsType {
	if o == nil || IsNil(o.Warnings) {
		var ret WarningsType
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutLocatorCodesTemplateRequest) GetWarningsOk() (*WarningsType, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *PutLocatorCodesTemplateRequest) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given WarningsType and assigns it to the Warnings field.
func (o *PutLocatorCodesTemplateRequest) SetWarnings(v WarningsType) {
	o.Warnings = &v
}

func (o PutLocatorCodesTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutLocatorCodesTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.LocatorCodes) {
		toSerialize["locatorCodes"] = o.LocatorCodes
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

type NullablePutLocatorCodesTemplateRequest struct {
	value *PutLocatorCodesTemplateRequest
	isSet bool
}

func (v NullablePutLocatorCodesTemplateRequest) Get() *PutLocatorCodesTemplateRequest {
	return v.value
}

func (v *NullablePutLocatorCodesTemplateRequest) Set(val *PutLocatorCodesTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutLocatorCodesTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutLocatorCodesTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutLocatorCodesTemplateRequest(val *PutLocatorCodesTemplateRequest) *NullablePutLocatorCodesTemplateRequest {
	return &NullablePutLocatorCodesTemplateRequest{value: val, isSet: true}
}

func (v NullablePutLocatorCodesTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutLocatorCodesTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


