/*
OPERA Cloud Front Desk Operations Service

APIs to cater for Front Desk Operations and Front Desk Statistic functionality in OPERA Cloud. <br /><br /> Front Desk features some of the most commonly used operations in OPERA Cloud, such as managing guest arrivals, managing in-house guests, and managing guest departures. Some additional tasks you can complete from the Front Desk menu are room searches, room assignments, and quick check outs as well as opening folios, creating registration cards, setting wake up calls, and sending messages to guests.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>

API version: 23.2
Contact: hospitality_apis_ww_grp@oracle.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fof

import (
	"encoding/json"
)

// checks if the SwapRooms type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SwapRooms{}

// SwapRooms To quickly swap or shift rooms for two reservations that are for the same arrival date and room type
type SwapRooms struct {
	Links *Links `json:"links,omitempty"`
	SourceRoom *StayRoominfo `json:"sourceRoom,omitempty"`
	TargetRoom *StayRoominfo `json:"targetRoom,omitempty"`
	Warnings *WarningsType `json:"warnings,omitempty"`
}

// NewSwapRooms instantiates a new SwapRooms object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwapRooms() *SwapRooms {
	this := SwapRooms{}
	return &this
}

// NewSwapRoomsWithDefaults instantiates a new SwapRooms object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwapRoomsWithDefaults() *SwapRooms {
	this := SwapRooms{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *SwapRooms) GetLinks() Links {
	if o == nil || IsNil(o.Links) {
		var ret Links
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRooms) GetLinksOk() (*Links, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *SwapRooms) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Links and assigns it to the Links field.
func (o *SwapRooms) SetLinks(v Links) {
	o.Links = &v
}

// GetSourceRoom returns the SourceRoom field value if set, zero value otherwise.
func (o *SwapRooms) GetSourceRoom() StayRoominfo {
	if o == nil || IsNil(o.SourceRoom) {
		var ret StayRoominfo
		return ret
	}
	return *o.SourceRoom
}

// GetSourceRoomOk returns a tuple with the SourceRoom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRooms) GetSourceRoomOk() (*StayRoominfo, bool) {
	if o == nil || IsNil(o.SourceRoom) {
		return nil, false
	}
	return o.SourceRoom, true
}

// HasSourceRoom returns a boolean if a field has been set.
func (o *SwapRooms) HasSourceRoom() bool {
	if o != nil && !IsNil(o.SourceRoom) {
		return true
	}

	return false
}

// SetSourceRoom gets a reference to the given StayRoominfo and assigns it to the SourceRoom field.
func (o *SwapRooms) SetSourceRoom(v StayRoominfo) {
	o.SourceRoom = &v
}

// GetTargetRoom returns the TargetRoom field value if set, zero value otherwise.
func (o *SwapRooms) GetTargetRoom() StayRoominfo {
	if o == nil || IsNil(o.TargetRoom) {
		var ret StayRoominfo
		return ret
	}
	return *o.TargetRoom
}

// GetTargetRoomOk returns a tuple with the TargetRoom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRooms) GetTargetRoomOk() (*StayRoominfo, bool) {
	if o == nil || IsNil(o.TargetRoom) {
		return nil, false
	}
	return o.TargetRoom, true
}

// HasTargetRoom returns a boolean if a field has been set.
func (o *SwapRooms) HasTargetRoom() bool {
	if o != nil && !IsNil(o.TargetRoom) {
		return true
	}

	return false
}

// SetTargetRoom gets a reference to the given StayRoominfo and assigns it to the TargetRoom field.
func (o *SwapRooms) SetTargetRoom(v StayRoominfo) {
	o.TargetRoom = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *SwapRooms) GetWarnings() WarningsType {
	if o == nil || IsNil(o.Warnings) {
		var ret WarningsType
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwapRooms) GetWarningsOk() (*WarningsType, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *SwapRooms) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given WarningsType and assigns it to the Warnings field.
func (o *SwapRooms) SetWarnings(v WarningsType) {
	o.Warnings = &v
}

func (o SwapRooms) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SwapRooms) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.SourceRoom) {
		toSerialize["sourceRoom"] = o.SourceRoom
	}
	if !IsNil(o.TargetRoom) {
		toSerialize["targetRoom"] = o.TargetRoom
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

type NullableSwapRooms struct {
	value *SwapRooms
	isSet bool
}

func (v NullableSwapRooms) Get() *SwapRooms {
	return v.value
}

func (v *NullableSwapRooms) Set(val *SwapRooms) {
	v.value = val
	v.isSet = true
}

func (v NullableSwapRooms) IsSet() bool {
	return v.isSet
}

func (v *NullableSwapRooms) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwapRooms(val *SwapRooms) *NullableSwapRooms {
	return &NullableSwapRooms{value: val, isSet: true}
}

func (v NullableSwapRooms) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwapRooms) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


