/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Front Desk Operations Service
 * APIs to cater for Front Desk Operations and Front Desk Statistic functionality in OPERA Cloud. <br /><br /> Front Desk features some of the most commonly used operations in OPERA Cloud, such as managing guest arrivals, managing in-house guests, and managing guest departures. Some additional tasks you can complete from the Front Desk menu are room searches, room assignments, and quick check outs as well as opening folios, creating registration cards, setting wake up calls, and sending messages to guests.<br /><br /> Compatible with OPERA Cloud release 21.5.0.0.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2022 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 21.5.0.0
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UniqueIDType } from './UniqueIDType';
import {
    UniqueIDTypeFromJSON,
    UniqueIDTypeFromJSONTyped,
    UniqueIDTypeToJSON,
} from './UniqueIDType';

/**
 * Authorizer Information
 * @export
 * @interface AuthorizerInfoType
 */
export interface AuthorizerInfoType {
    /**
     * 
     * @type {UniqueIDType}
     * @memberof AuthorizerInfoType
     */
    authorizerId?: UniqueIDType;
    /**
     * Application user name of the authorizer
     * @type {string}
     * @memberof AuthorizerInfoType
     */
    authorizerUserName?: string;
    /**
     * Full name of the authorizer.
     * @type {string}
     * @memberof AuthorizerInfoType
     */
    authorizerName?: string;
    /**
     * Rate code of the authorizer.
     * @type {string}
     * @memberof AuthorizerInfoType
     */
    authorizerRateCode?: string;
    /**
     * Indicates whether user has the choice to have reservation inherit rate code from the authorizer.
     * @type {boolean}
     * @memberof AuthorizerInfoType
     */
    inheritAuthorizerRateCode?: boolean;
}

/**
 * Check if a given object implements the AuthorizerInfoType interface.
 */
export function instanceOfAuthorizerInfoType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthorizerInfoTypeFromJSON(json: any): AuthorizerInfoType {
    return AuthorizerInfoTypeFromJSONTyped(json, false);
}

export function AuthorizerInfoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizerInfoType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorizerId': !exists(json, 'authorizerId') ? undefined : UniqueIDTypeFromJSON(json['authorizerId']),
        'authorizerUserName': !exists(json, 'authorizerUserName') ? undefined : json['authorizerUserName'],
        'authorizerName': !exists(json, 'authorizerName') ? undefined : json['authorizerName'],
        'authorizerRateCode': !exists(json, 'authorizerRateCode') ? undefined : json['authorizerRateCode'],
        'inheritAuthorizerRateCode': !exists(json, 'inheritAuthorizerRateCode') ? undefined : json['inheritAuthorizerRateCode'],
    };
}

export function AuthorizerInfoTypeToJSON(value?: AuthorizerInfoType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authorizerId': UniqueIDTypeToJSON(value.authorizerId),
        'authorizerUserName': value.authorizerUserName,
        'authorizerName': value.authorizerName,
        'authorizerRateCode': value.authorizerRateCode,
        'inheritAuthorizerRateCode': value.inheritAuthorizerRateCode,
    };
}

