/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Integration Configuration API
 * APIs catering to Integration Configuration in OPERA Cloud.  Operations such as get Hotel Interface Types, or get UDF mappings can be found in this module.<br /><br /> Compatible with OPERA Cloud release 23.4.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.4
 * Contact: hospitality-integrations_ww@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConfiguredExternalDevices } from './ConfiguredExternalDevices';
import {
    ConfiguredExternalDevicesFromJSON,
    ConfiguredExternalDevicesFromJSONTyped,
    ConfiguredExternalDevicesToJSON,
} from './ConfiguredExternalDevices';
import type { InstanceLink } from './InstanceLink';
import {
    InstanceLinkFromJSON,
    InstanceLinkFromJSONTyped,
    InstanceLinkToJSON,
} from './InstanceLink';
import type { WarningType } from './WarningType';
import {
    WarningTypeFromJSON,
    WarningTypeFromJSONTyped,
    WarningTypeToJSON,
} from './WarningType';

/**
 * 
 * @export
 * @interface FetchedConfiguredExternalDevices
 */
export interface FetchedConfiguredExternalDevices {
    /**
     * 
     * @type {ConfiguredExternalDevices}
     * @memberof FetchedConfiguredExternalDevices
     */
    configuredExternalDevices?: ConfiguredExternalDevices;
    /**
     * 
     * @type {Array<InstanceLink>}
     * @memberof FetchedConfiguredExternalDevices
     */
    links?: Array<InstanceLink>;
    /**
     * Used in conjunction with the Success element to define a business error.
     * @type {Array<WarningType>}
     * @memberof FetchedConfiguredExternalDevices
     */
    warnings?: Array<WarningType>;
}

/**
 * Check if a given object implements the FetchedConfiguredExternalDevices interface.
 */
export function instanceOfFetchedConfiguredExternalDevices(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FetchedConfiguredExternalDevicesFromJSON(json: any): FetchedConfiguredExternalDevices {
    return FetchedConfiguredExternalDevicesFromJSONTyped(json, false);
}

export function FetchedConfiguredExternalDevicesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchedConfiguredExternalDevices {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'configuredExternalDevices': !exists(json, 'configuredExternalDevices') ? undefined : ConfiguredExternalDevicesFromJSON(json['configuredExternalDevices']),
        'links': !exists(json, 'links') ? undefined : ((json['links'] as Array<any>).map(InstanceLinkFromJSON)),
        'warnings': !exists(json, 'warnings') ? undefined : ((json['warnings'] as Array<any>).map(WarningTypeFromJSON)),
    };
}

export function FetchedConfiguredExternalDevicesToJSON(value?: FetchedConfiguredExternalDevices | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'configuredExternalDevices': ConfiguredExternalDevicesToJSON(value.configuredExternalDevices),
        'links': value.links === undefined ? undefined : ((value.links as Array<any>).map(InstanceLinkToJSON)),
        'warnings': value.warnings === undefined ? undefined : ((value.warnings as Array<any>).map(WarningTypeToJSON)),
    };
}

