/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Enterprise Configuration API
 * APIs to cater for Enterprise Configuration functionality in OPERA Cloud. <br /><br In this module, you can configure a variety of options related to your properties such as their locations, facilities, and local attractions. The available options are dependant on the active controls at your property.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { PropertyTypesType } from './PropertyTypesType';
import {
    PropertyTypesTypeFromJSON,
    PropertyTypesTypeFromJSONTyped,
    PropertyTypesTypeToJSON,
} from './PropertyTypesType';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * 
 * @export
 * @interface PutPropertyTypesRequest
 */
export interface PutPropertyTypesRequest {
    /**
     * 
     * @type {Links}
     * @memberof PutPropertyTypesRequest
     */
    links?: Links;
    /**
     * 
     * @type {PropertyTypesType}
     * @memberof PutPropertyTypesRequest
     */
    propertyTypes?: PropertyTypesType;
    /**
     * 
     * @type {WarningsType}
     * @memberof PutPropertyTypesRequest
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the PutPropertyTypesRequest interface.
 */
export function instanceOfPutPropertyTypesRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PutPropertyTypesRequestFromJSON(json: any): PutPropertyTypesRequest {
    return PutPropertyTypesRequestFromJSONTyped(json, false);
}

export function PutPropertyTypesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutPropertyTypesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'propertyTypes': !exists(json, 'propertyTypes') ? undefined : PropertyTypesTypeFromJSON(json['propertyTypes']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function PutPropertyTypesRequestToJSON(value?: PutPropertyTypesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': LinksToJSON(value.links),
        'propertyTypes': PropertyTypesTypeToJSON(value.propertyTypes),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

