/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Export Configuration API
 * APIs catering to the managing export master data configuration. The exports feature in OPERA Cloud provides the ability to create and export data files, such as back office data, to third-party interfaces and receiving systems.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A flag to set export to be run in Night Audit.
 * @export
 * @interface ExportGenerateConfigurationTypeNightAudit
 */
export interface ExportGenerateConfigurationTypeNightAudit {
    /**
     * Day of the week, when the export routine is run in the night audit and the NA_FREQUENCY is set to 'Day of Week'.
     * @type {string}
     * @memberof ExportGenerateConfigurationTypeNightAudit
     */
    nightAuditExportDetail?: string;
    /**
     * The frequency at which export should be generated. Eg. Nightly, End of Month or End of Year.
     * @type {string}
     * @memberof ExportGenerateConfigurationTypeNightAudit
     */
    nightAuditFrequency?: string;
    /**
     * A flag to set export to be run in Night Audit.
     * @type {boolean}
     * @memberof ExportGenerateConfigurationTypeNightAudit
     */
    runInNightAudit?: boolean;
}

/**
 * Check if a given object implements the ExportGenerateConfigurationTypeNightAudit interface.
 */
export function instanceOfExportGenerateConfigurationTypeNightAudit(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExportGenerateConfigurationTypeNightAuditFromJSON(json: any): ExportGenerateConfigurationTypeNightAudit {
    return ExportGenerateConfigurationTypeNightAuditFromJSONTyped(json, false);
}

export function ExportGenerateConfigurationTypeNightAuditFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportGenerateConfigurationTypeNightAudit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nightAuditExportDetail': !exists(json, 'nightAuditExportDetail') ? undefined : json['nightAuditExportDetail'],
        'nightAuditFrequency': !exists(json, 'nightAuditFrequency') ? undefined : json['nightAuditFrequency'],
        'runInNightAudit': !exists(json, 'runInNightAudit') ? undefined : json['runInNightAudit'],
    };
}

export function ExportGenerateConfigurationTypeNightAuditToJSON(value?: ExportGenerateConfigurationTypeNightAudit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nightAuditExportDetail': value.nightAuditExportDetail,
        'nightAuditFrequency': value.nightAuditFrequency,
        'runInNightAudit': value.runInNightAudit,
    };
}

