/*
OPERA Cloud Cashiering API

APIs to cater for Cashiering related functionality in OPERA Cloud.<br /><br /> Cashiering provides access to a guest folio, posting journals, receipt histories, currency calculations, credit card settlements, and check a guest out.<br /><br /> Compatible with OPERA Cloud release 26.2.0.0.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2026 Oracle and/or its affiliates.</p>

API version: 26.2.0.0
Contact: hospitality_apis_ww_grp@oracle.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csh

import (
	"encoding/json"
)

// checks if the CcAuthorizationInstructionsCriteria type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CcAuthorizationInstructionsCriteria{}

// CcAuthorizationInstructionsCriteria Fetch credit card authorization instructions.
type CcAuthorizationInstructionsCriteria struct {
	Criteria *CcAuthorizationInstructionsCriteriaType `json:"criteria,omitempty"`
	Links []InstanceLink `json:"links,omitempty"`
	// Used in conjunction with the Success element to define a business error.
	Warnings []WarningType `json:"warnings,omitempty"`
}

// NewCcAuthorizationInstructionsCriteria instantiates a new CcAuthorizationInstructionsCriteria object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCcAuthorizationInstructionsCriteria() *CcAuthorizationInstructionsCriteria {
	this := CcAuthorizationInstructionsCriteria{}
	return &this
}

// NewCcAuthorizationInstructionsCriteriaWithDefaults instantiates a new CcAuthorizationInstructionsCriteria object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCcAuthorizationInstructionsCriteriaWithDefaults() *CcAuthorizationInstructionsCriteria {
	this := CcAuthorizationInstructionsCriteria{}
	return &this
}

// GetCriteria returns the Criteria field value if set, zero value otherwise.
func (o *CcAuthorizationInstructionsCriteria) GetCriteria() CcAuthorizationInstructionsCriteriaType {
	if o == nil || IsNil(o.Criteria) {
		var ret CcAuthorizationInstructionsCriteriaType
		return ret
	}
	return *o.Criteria
}

// GetCriteriaOk returns a tuple with the Criteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CcAuthorizationInstructionsCriteria) GetCriteriaOk() (*CcAuthorizationInstructionsCriteriaType, bool) {
	if o == nil || IsNil(o.Criteria) {
		return nil, false
	}
	return o.Criteria, true
}

// HasCriteria returns a boolean if a field has been set.
func (o *CcAuthorizationInstructionsCriteria) HasCriteria() bool {
	if o != nil && !IsNil(o.Criteria) {
		return true
	}

	return false
}

// SetCriteria gets a reference to the given CcAuthorizationInstructionsCriteriaType and assigns it to the Criteria field.
func (o *CcAuthorizationInstructionsCriteria) SetCriteria(v CcAuthorizationInstructionsCriteriaType) {
	o.Criteria = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CcAuthorizationInstructionsCriteria) GetLinks() []InstanceLink {
	if o == nil || IsNil(o.Links) {
		var ret []InstanceLink
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CcAuthorizationInstructionsCriteria) GetLinksOk() ([]InstanceLink, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CcAuthorizationInstructionsCriteria) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []InstanceLink and assigns it to the Links field.
func (o *CcAuthorizationInstructionsCriteria) SetLinks(v []InstanceLink) {
	o.Links = v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *CcAuthorizationInstructionsCriteria) GetWarnings() []WarningType {
	if o == nil || IsNil(o.Warnings) {
		var ret []WarningType
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CcAuthorizationInstructionsCriteria) GetWarningsOk() ([]WarningType, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *CcAuthorizationInstructionsCriteria) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []WarningType and assigns it to the Warnings field.
func (o *CcAuthorizationInstructionsCriteria) SetWarnings(v []WarningType) {
	o.Warnings = v
}

func (o CcAuthorizationInstructionsCriteria) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CcAuthorizationInstructionsCriteria) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Criteria) {
		toSerialize["criteria"] = o.Criteria
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

type NullableCcAuthorizationInstructionsCriteria struct {
	value *CcAuthorizationInstructionsCriteria
	isSet bool
}

func (v NullableCcAuthorizationInstructionsCriteria) Get() *CcAuthorizationInstructionsCriteria {
	return v.value
}

func (v *NullableCcAuthorizationInstructionsCriteria) Set(val *CcAuthorizationInstructionsCriteria) {
	v.value = val
	v.isSet = true
}

func (v NullableCcAuthorizationInstructionsCriteria) IsSet() bool {
	return v.isSet
}

func (v *NullableCcAuthorizationInstructionsCriteria) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCcAuthorizationInstructionsCriteria(val *CcAuthorizationInstructionsCriteria) *NullableCcAuthorizationInstructionsCriteria {
	return &NullableCcAuthorizationInstructionsCriteria{value: val, isSet: true}
}

func (v NullableCcAuthorizationInstructionsCriteria) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCcAuthorizationInstructionsCriteria) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


