/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Room Configuration API
 * APIs to cater for room configuration, such as configuring room types, room Classes, creating new room features, or updating housekeeping room maintenance reasons.<br /><br /> Compatible with OPERA Cloud release 21.5.0.0.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2022 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 21.5.0.0
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Simple type for storing frequency type.
 * @export
 */
export const FrequencyTypeType = {
    Everyday: 'Everyday',
    EveryXDays: 'EveryXDays',
    CustomSchedule: 'CustomSchedule',
    DepartureDayOnly: 'DepartureDayOnly',
    ArrivalDayOnly: 'ArrivalDayOnly',
    NotRequired: 'NotRequired',
    SpecificDays: 'SpecificDays'
} as const;
export type FrequencyTypeType = typeof FrequencyTypeType[keyof typeof FrequencyTypeType];


export function FrequencyTypeTypeFromJSON(json: any): FrequencyTypeType {
    return FrequencyTypeTypeFromJSONTyped(json, false);
}

export function FrequencyTypeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FrequencyTypeType {
    return json as FrequencyTypeType;
}

export function FrequencyTypeTypeToJSON(value?: FrequencyTypeType | null): any {
    return value as any;
}

