/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Rate API
 * APIs to cater for Rate Availability functionality in OPERA Cloud. <br /><br /> Rate Management provides all the tools you need to effectively define and manage the rate structures for a property in OPERA Cloud. Some of the things you can do include creating and managing rate codes, rate classes, rate categories, display sets, rate strategies, as well as managing promotion groups and codes.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HotelPackageForecastGroupsType } from './HotelPackageForecastGroupsType';
import {
    HotelPackageForecastGroupsTypeFromJSON,
    HotelPackageForecastGroupsTypeFromJSONTyped,
    HotelPackageForecastGroupsTypeToJSON,
} from './HotelPackageForecastGroupsType';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * Request object for modifying package forecast groups for a hotel.
 * @export
 * @interface HotelPackageForecastGroupsToChange
 */
export interface HotelPackageForecastGroupsToChange {
    /**
     * 
     * @type {HotelPackageForecastGroupsType}
     * @memberof HotelPackageForecastGroupsToChange
     */
    hotelPackageForecastGroups?: HotelPackageForecastGroupsType;
    /**
     * 
     * @type {Links}
     * @memberof HotelPackageForecastGroupsToChange
     */
    links?: Links;
    /**
     * 
     * @type {WarningsType}
     * @memberof HotelPackageForecastGroupsToChange
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the HotelPackageForecastGroupsToChange interface.
 */
export function instanceOfHotelPackageForecastGroupsToChange(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HotelPackageForecastGroupsToChangeFromJSON(json: any): HotelPackageForecastGroupsToChange {
    return HotelPackageForecastGroupsToChangeFromJSONTyped(json, false);
}

export function HotelPackageForecastGroupsToChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HotelPackageForecastGroupsToChange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hotelPackageForecastGroups': !exists(json, 'hotelPackageForecastGroups') ? undefined : HotelPackageForecastGroupsTypeFromJSON(json['hotelPackageForecastGroups']),
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function HotelPackageForecastGroupsToChangeToJSON(value?: HotelPackageForecastGroupsToChange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hotelPackageForecastGroups': HotelPackageForecastGroupsTypeToJSON(value.hotelPackageForecastGroups),
        'links': LinksToJSON(value.links),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

