/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Rate API
 * APIs to cater for Rate Availability functionality in OPERA Cloud. <br /><br /> Rate Management provides all the tools you need to effectively define and manage the rate structures for a property in OPERA Cloud. Some of the things you can do include creating and managing rate codes, rate classes, rate categories, display sets, rate strategies, as well as managing promotion groups and codes.<br /><br /> Compatible with OPERA Cloud release 24.4.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2024 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 24.4
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PropertyPromotionCodeType } from './PropertyPromotionCodeType';
import {
    PropertyPromotionCodeTypeFromJSON,
    PropertyPromotionCodeTypeFromJSONTyped,
    PropertyPromotionCodeTypeToJSON,
} from './PropertyPromotionCodeType';

/**
 * Collection of Property promotions.
 * @export
 * @interface PropertyPromotionCodesPropertyPromotionCodes
 */
export interface PropertyPromotionCodesPropertyPromotionCodes {
    /**
     * A property promotion.
     * @type {Array<PropertyPromotionCodeType>}
     * @memberof PropertyPromotionCodesPropertyPromotionCodes
     */
    propertyPromotionCodes?: Array<PropertyPromotionCodeType>;
    /**
     * Evaluated total page count based on the requested max fetch count.
     * @type {number}
     * @memberof PropertyPromotionCodesPropertyPromotionCodes
     */
    totalPages?: number;
    /**
     * Indicates whether all the records are included in the response or not. Absence of the attribute values should be consider as all rows fetched in the response.
     * @type {boolean}
     * @memberof PropertyPromotionCodesPropertyPromotionCodes
     */
    hasMore?: boolean;
    /**
     * Total number of rows queried
     * @type {number}
     * @memberof PropertyPromotionCodesPropertyPromotionCodes
     */
    totalResults?: number;
    /**
     * Total number of rows returned
     * @type {number}
     * @memberof PropertyPromotionCodesPropertyPromotionCodes
     */
    count?: number;
    /**
     * Index or initial index of the set(page) being requested. If the index goes out of the bounds of the total set count then no data will be returned.
     * @type {number}
     * @memberof PropertyPromotionCodesPropertyPromotionCodes
     */
    offset?: number;
    /**
     * Indicates maximum number of records a Web Service should return.
     * @type {number}
     * @memberof PropertyPromotionCodesPropertyPromotionCodes
     */
    limit?: number;
}

/**
 * Check if a given object implements the PropertyPromotionCodesPropertyPromotionCodes interface.
 */
export function instanceOfPropertyPromotionCodesPropertyPromotionCodes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PropertyPromotionCodesPropertyPromotionCodesFromJSON(json: any): PropertyPromotionCodesPropertyPromotionCodes {
    return PropertyPromotionCodesPropertyPromotionCodesFromJSONTyped(json, false);
}

export function PropertyPromotionCodesPropertyPromotionCodesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyPromotionCodesPropertyPromotionCodes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'propertyPromotionCodes': !exists(json, 'propertyPromotionCodes') ? undefined : ((json['propertyPromotionCodes'] as Array<any>).map(PropertyPromotionCodeTypeFromJSON)),
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'hasMore': !exists(json, 'hasMore') ? undefined : json['hasMore'],
        'totalResults': !exists(json, 'totalResults') ? undefined : json['totalResults'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
    };
}

export function PropertyPromotionCodesPropertyPromotionCodesToJSON(value?: PropertyPromotionCodesPropertyPromotionCodes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'propertyPromotionCodes': value.propertyPromotionCodes === undefined ? undefined : ((value.propertyPromotionCodes as Array<any>).map(PropertyPromotionCodeTypeToJSON)),
        'totalPages': value.totalPages,
        'hasMore': value.hasMore,
        'totalResults': value.totalResults,
        'count': value.count,
        'offset': value.offset,
        'limit': value.limit,
    };
}

