/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Rate API
 * APIs to cater for Rate Availability functionality in OPERA Cloud. <br /><br /> Rate Management provides all the tools you need to effectively define and manage the rate structures for a property in OPERA Cloud. Some of the things you can do include creating and managing rate codes, rate classes, rate categories, display sets, rate strategies, as well as managing promotion groups and codes.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceLink } from './InstanceLink';
import {
    InstanceLinkFromJSON,
    InstanceLinkFromJSONTyped,
    InstanceLinkToJSON,
} from './InstanceLink';
import type { UpdateRatePlanSchedulesType } from './UpdateRatePlanSchedulesType';
import {
    UpdateRatePlanSchedulesTypeFromJSON,
    UpdateRatePlanSchedulesTypeFromJSONTyped,
    UpdateRatePlanSchedulesTypeToJSON,
} from './UpdateRatePlanSchedulesType';
import type { WarningType } from './WarningType';
import {
    WarningTypeFromJSON,
    WarningTypeFromJSONTyped,
    WarningTypeToJSON,
} from './WarningType';

/**
 * Request object to change rate plan schedules.
 * @export
 * @interface RatePlanSchedules
 */
export interface RatePlanSchedules {
    /**
     * Used for codes in the OPERA Code tables. Possible values of this pattern are 1, 101, 101.EQP, or 101.EQP.X.
     * @type {string}
     * @memberof RatePlanSchedules
     */
    hotelId?: string;
    /**
     * 
     * @type {Array<InstanceLink>}
     * @memberof RatePlanSchedules
     */
    links?: Array<InstanceLink>;
    /**
     * Used for codes in the OPERA Code tables. Possible values of this pattern are 1, 101, 101.EQP, or 101.EQP.X.
     * @type {string}
     * @memberof RatePlanSchedules
     */
    ratePlanCode?: string;
    /**
     * List of rate plan schedules to be updated.
     * @type {Array<UpdateRatePlanSchedulesType>}
     * @memberof RatePlanSchedules
     */
    ratePlanScheduleList?: Array<UpdateRatePlanSchedulesType>;
    /**
     * Used in conjunction with the Success element to define a business error.
     * @type {Array<WarningType>}
     * @memberof RatePlanSchedules
     */
    warnings?: Array<WarningType>;
}

/**
 * Check if a given object implements the RatePlanSchedules interface.
 */
export function instanceOfRatePlanSchedules(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RatePlanSchedulesFromJSON(json: any): RatePlanSchedules {
    return RatePlanSchedulesFromJSONTyped(json, false);
}

export function RatePlanSchedulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatePlanSchedules {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hotelId': !exists(json, 'hotelId') ? undefined : json['hotelId'],
        'links': !exists(json, 'links') ? undefined : ((json['links'] as Array<any>).map(InstanceLinkFromJSON)),
        'ratePlanCode': !exists(json, 'ratePlanCode') ? undefined : json['ratePlanCode'],
        'ratePlanScheduleList': !exists(json, 'ratePlanScheduleList') ? undefined : ((json['ratePlanScheduleList'] as Array<any>).map(UpdateRatePlanSchedulesTypeFromJSON)),
        'warnings': !exists(json, 'warnings') ? undefined : ((json['warnings'] as Array<any>).map(WarningTypeFromJSON)),
    };
}

export function RatePlanSchedulesToJSON(value?: RatePlanSchedules | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hotelId': value.hotelId,
        'links': value.links === undefined ? undefined : ((value.links as Array<any>).map(InstanceLinkToJSON)),
        'ratePlanCode': value.ratePlanCode,
        'ratePlanScheduleList': value.ratePlanScheduleList === undefined ? undefined : ((value.ratePlanScheduleList as Array<any>).map(UpdateRatePlanSchedulesTypeToJSON)),
        'warnings': value.warnings === undefined ? undefined : ((value.warnings as Array<any>).map(WarningTypeToJSON)),
    };
}

