/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Rate API
 * APIs to cater for Rate Availability functionality in OPERA Cloud. <br /><br /> Rate Management provides all the tools you need to effectively define and manage the rate structures for a property in OPERA Cloud. Some of the things you can do include creating and managing rate codes, rate classes, rate categories, display sets, rate strategies, as well as managing promotion groups and codes.<br /><br /> Compatible with OPERA Cloud release 24.4.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2024 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 24.4
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HotelRateCategoryType } from './HotelRateCategoryType';
import {
    HotelRateCategoryTypeFromJSON,
    HotelRateCategoryTypeFromJSONTyped,
    HotelRateCategoryTypeToJSON,
} from './HotelRateCategoryType';
import type { InstanceLink } from './InstanceLink';
import {
    InstanceLinkFromJSON,
    InstanceLinkFromJSONTyped,
    InstanceLinkToJSON,
} from './InstanceLink';
import type { WarningType } from './WarningType';
import {
    WarningTypeFromJSON,
    WarningTypeFromJSONTyped,
    WarningTypeToJSON,
} from './WarningType';

/**
 * Request object for modifying a Rate Category for a property.
 * @export
 * @interface RateCategoryToBeChanged
 */
export interface RateCategoryToBeChanged {
    /**
     * 
     * @type {HotelRateCategoryType}
     * @memberof RateCategoryToBeChanged
     */
    hotelRateCategory?: HotelRateCategoryType;
    /**
     * 
     * @type {Array<InstanceLink>}
     * @memberof RateCategoryToBeChanged
     */
    links?: Array<InstanceLink>;
    /**
     * Used in conjunction with the Success element to define a business error.
     * @type {Array<WarningType>}
     * @memberof RateCategoryToBeChanged
     */
    warnings?: Array<WarningType>;
}

/**
 * Check if a given object implements the RateCategoryToBeChanged interface.
 */
export function instanceOfRateCategoryToBeChanged(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RateCategoryToBeChangedFromJSON(json: any): RateCategoryToBeChanged {
    return RateCategoryToBeChangedFromJSONTyped(json, false);
}

export function RateCategoryToBeChangedFromJSONTyped(json: any, ignoreDiscriminator: boolean): RateCategoryToBeChanged {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hotelRateCategory': !exists(json, 'hotelRateCategory') ? undefined : HotelRateCategoryTypeFromJSON(json['hotelRateCategory']),
        'links': !exists(json, 'links') ? undefined : ((json['links'] as Array<any>).map(InstanceLinkFromJSON)),
        'warnings': !exists(json, 'warnings') ? undefined : ((json['warnings'] as Array<any>).map(WarningTypeFromJSON)),
    };
}

export function RateCategoryToBeChangedToJSON(value?: RateCategoryToBeChanged | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hotelRateCategory': HotelRateCategoryTypeToJSON(value.hotelRateCategory),
        'links': value.links === undefined ? undefined : ((value.links as Array<any>).map(InstanceLinkToJSON)),
        'warnings': value.warnings === undefined ? undefined : ((value.warnings as Array<any>).map(WarningTypeToJSON)),
    };
}

