/*
OPERA Cloud API for Customer Management Service

This API deals with the different aspect of the CustomerManagement.<br /><br /> Compatible with OPERA Cloud release 26.2.0.0.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2026 Oracle and/or its affiliates.</p>

API version: 26.2.0.0
Contact: hospitality_apis_ww_grp@oracle.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cms

import (
	"encoding/json"
	"fmt"
)

// TrackItGroupEnum the model 'TrackItGroupEnum'
type TrackItGroupEnum string

// List of trackItGroupEnum
const (
	TRACKITGROUPENUM_PARCEL TrackItGroupEnum = "Parcel"
	TRACKITGROUPENUM_VALET TrackItGroupEnum = "Valet"
	TRACKITGROUPENUM_BAGGAGE TrackItGroupEnum = "Baggage"
	TRACKITGROUPENUM_LOST TrackItGroupEnum = "Lost"
)

// All allowed values of TrackItGroupEnum enum
var AllowedTrackItGroupEnumEnumValues = []TrackItGroupEnum{
	"Parcel",
	"Valet",
	"Baggage",
	"Lost",
}

func (v *TrackItGroupEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TrackItGroupEnum(value)
	for _, existing := range AllowedTrackItGroupEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TrackItGroupEnum", value)
}

// NewTrackItGroupEnumFromValue returns a pointer to a valid TrackItGroupEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTrackItGroupEnumFromValue(v string) (*TrackItGroupEnum, error) {
	ev := TrackItGroupEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TrackItGroupEnum: valid values are %v", v, AllowedTrackItGroupEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TrackItGroupEnum) IsValid() bool {
	for _, existing := range AllowedTrackItGroupEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to trackItGroupEnum value
func (v TrackItGroupEnum) Ptr() *TrackItGroupEnum {
	return &v
}

type NullableTrackItGroupEnum struct {
	value *TrackItGroupEnum
	isSet bool
}

func (v NullableTrackItGroupEnum) Get() *TrackItGroupEnum {
	return v.value
}

func (v *NullableTrackItGroupEnum) Set(val *TrackItGroupEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackItGroupEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackItGroupEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackItGroupEnum(val *TrackItGroupEnum) *NullableTrackItGroupEnum {
	return &NullableTrackItGroupEnum{value: val, isSet: true}
}

func (v NullableTrackItGroupEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackItGroupEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

