/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Reservation Master Data Management API
 * APIs to cater for Reservation Configuration in OPERA Cloud. In this module you can retrieve, create, modify or delete configuration related to Reservations, Blocks and Leisure Management.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { SourceCodeType } from './SourceCodeType';
import {
    SourceCodeTypeFromJSON,
    SourceCodeTypeFromJSONTyped,
    SourceCodeTypeToJSON,
} from './SourceCodeType';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * 
 * @export
 * @interface ChangeSourceCodeRequest
 */
export interface ChangeSourceCodeRequest {
    /**
     * 
     * @type {Links}
     * @memberof ChangeSourceCodeRequest
     */
    links?: Links;
    /**
     * 
     * @type {SourceCodeType}
     * @memberof ChangeSourceCodeRequest
     */
    sourceCode?: SourceCodeType;
    /**
     * 
     * @type {WarningsType}
     * @memberof ChangeSourceCodeRequest
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the ChangeSourceCodeRequest interface.
 */
export function instanceOfChangeSourceCodeRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChangeSourceCodeRequestFromJSON(json: any): ChangeSourceCodeRequest {
    return ChangeSourceCodeRequestFromJSONTyped(json, false);
}

export function ChangeSourceCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeSourceCodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'sourceCode': !exists(json, 'sourceCode') ? undefined : SourceCodeTypeFromJSON(json['sourceCode']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function ChangeSourceCodeRequestToJSON(value?: ChangeSourceCodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': LinksToJSON(value.links),
        'sourceCode': SourceCodeTypeToJSON(value.sourceCode),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

