/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Reservation Master Data Management API
 * APIs to cater for Reservation Configuration in OPERA Cloud. In this module you can retrieve, create, modify or delete configuration related to Reservations, Blocks and Leisure Management.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CopySchedulesCriteriaType } from './CopySchedulesCriteriaType';
import {
    CopySchedulesCriteriaTypeFromJSON,
    CopySchedulesCriteriaTypeFromJSONTyped,
    CopySchedulesCriteriaTypeToJSON,
} from './CopySchedulesCriteriaType';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * 
 * @export
 * @interface CopyPolicySchedulesRequest
 */
export interface CopyPolicySchedulesRequest {
    /**
     * 
     * @type {CopySchedulesCriteriaType}
     * @memberof CopyPolicySchedulesRequest
     */
    criteria?: CopySchedulesCriteriaType;
    /**
     * 
     * @type {Links}
     * @memberof CopyPolicySchedulesRequest
     */
    links?: Links;
    /**
     * 
     * @type {WarningsType}
     * @memberof CopyPolicySchedulesRequest
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the CopyPolicySchedulesRequest interface.
 */
export function instanceOfCopyPolicySchedulesRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CopyPolicySchedulesRequestFromJSON(json: any): CopyPolicySchedulesRequest {
    return CopyPolicySchedulesRequestFromJSONTyped(json, false);
}

export function CopyPolicySchedulesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopyPolicySchedulesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'criteria': !exists(json, 'criteria') ? undefined : CopySchedulesCriteriaTypeFromJSON(json['criteria']),
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function CopyPolicySchedulesRequestToJSON(value?: CopyPolicySchedulesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'criteria': CopySchedulesCriteriaTypeToJSON(value.criteria),
        'links': LinksToJSON(value.links),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

