/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Reservation Master Data Management API
 * APIs to cater for Reservation Configuration in OPERA Cloud. In this module you can retrieve, create, modify or delete configuration related to Reservations, Blocks and Leisure Management.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { OriginCodesType } from './OriginCodesType';
import {
    OriginCodesTypeFromJSON,
    OriginCodesTypeFromJSONTyped,
    OriginCodesTypeToJSON,
} from './OriginCodesType';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * Response object for fetching Origin Codes.
 * @export
 * @interface OriginCodesDetails
 */
export interface OriginCodesDetails {
    /**
     * 
     * @type {Links}
     * @memberof OriginCodesDetails
     */
    links?: Links;
    /**
     * 
     * @type {OriginCodesType}
     * @memberof OriginCodesDetails
     */
    originCodes?: OriginCodesType;
    /**
     * 
     * @type {WarningsType}
     * @memberof OriginCodesDetails
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the OriginCodesDetails interface.
 */
export function instanceOfOriginCodesDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OriginCodesDetailsFromJSON(json: any): OriginCodesDetails {
    return OriginCodesDetailsFromJSONTyped(json, false);
}

export function OriginCodesDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OriginCodesDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'originCodes': !exists(json, 'originCodes') ? undefined : OriginCodesTypeFromJSON(json['originCodes']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function OriginCodesDetailsToJSON(value?: OriginCodesDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': LinksToJSON(value.links),
        'originCodes': OriginCodesTypeToJSON(value.originCodes),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

