/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Reservation Master Data Management API
 * APIs to cater for Reservation Configuration in OPERA Cloud. In this module you can retrieve, create, modify or delete configuration related to Reservations, Blocks and Leisure Management.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { ScriptsType } from './ScriptsType';
import {
    ScriptsTypeFromJSON,
    ScriptsTypeFromJSONTyped,
    ScriptsTypeToJSON,
} from './ScriptsType';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * Request object for changing Scripts.
 * @export
 * @interface ScriptsToBeChanged
 */
export interface ScriptsToBeChanged {
    /**
     * 
     * @type {Links}
     * @memberof ScriptsToBeChanged
     */
    links?: Links;
    /**
     * 
     * @type {ScriptsType}
     * @memberof ScriptsToBeChanged
     */
    scripts?: ScriptsType;
    /**
     * 
     * @type {WarningsType}
     * @memberof ScriptsToBeChanged
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the ScriptsToBeChanged interface.
 */
export function instanceOfScriptsToBeChanged(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScriptsToBeChangedFromJSON(json: any): ScriptsToBeChanged {
    return ScriptsToBeChangedFromJSONTyped(json, false);
}

export function ScriptsToBeChangedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScriptsToBeChanged {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'scripts': !exists(json, 'scripts') ? undefined : ScriptsTypeFromJSON(json['scripts']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function ScriptsToBeChangedToJSON(value?: ScriptsToBeChanged | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': LinksToJSON(value.links),
        'scripts': ScriptsTypeToJSON(value.scripts),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

