/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Block API
 * APIs to cater for Business Block functionality in OPERA Cloud. <br /><br /> A block is a group of rooms held for guests who are attending an event, meeting, or function. You can create blocks for family reunions, business conferences, weddings, and so on. You can also set aside rooms for the event (block).<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlockRestrictionsType } from './BlockRestrictionsType';
import {
    BlockRestrictionsTypeFromJSON,
    BlockRestrictionsTypeFromJSONTyped,
    BlockRestrictionsTypeToJSON,
} from './BlockRestrictionsType';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * Response for FetchBlockRestrictions operation.
 * @export
 * @interface BlockRestrictions
 */
export interface BlockRestrictions {
    /**
     * 
     * @type {BlockRestrictionsType}
     * @memberof BlockRestrictions
     */
    blockRestrictions?: BlockRestrictionsType;
    /**
     * 
     * @type {Links}
     * @memberof BlockRestrictions
     */
    links?: Links;
    /**
     * 
     * @type {WarningsType}
     * @memberof BlockRestrictions
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the BlockRestrictions interface.
 */
export function instanceOfBlockRestrictions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BlockRestrictionsFromJSON(json: any): BlockRestrictions {
    return BlockRestrictionsFromJSONTyped(json, false);
}

export function BlockRestrictionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockRestrictions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blockRestrictions': !exists(json, 'blockRestrictions') ? undefined : BlockRestrictionsTypeFromJSON(json['blockRestrictions']),
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function BlockRestrictionsToJSON(value?: BlockRestrictions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blockRestrictions': BlockRestrictionsTypeToJSON(value.blockRestrictions),
        'links': LinksToJSON(value.links),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

