/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Customer Relationship Management Outbound API
 * APIs to cater for Customer Relationship Management external (outbound) functionality with OPERA. These APIs facilitate various operations related to getting data from an external system, and inserting it into OPERA.<br /><br /> Compatible with OPERA Cloud release 20.99.99.99.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 20.99.99.99
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { MemberInfoRSType } from './MemberInfoRSType';
import {
    MemberInfoRSTypeFromJSON,
    MemberInfoRSTypeFromJSONTyped,
    MemberInfoRSTypeToJSON,
} from './MemberInfoRSType';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * Response object for member info.
 * @export
 * @interface MemberInformation
 */
export interface MemberInformation {
    /**
     * 
     * @type {MemberInfoRSType}
     * @memberof MemberInformation
     */
    memberInfo?: MemberInfoRSType;
    /**
     * 
     * @type {Links}
     * @memberof MemberInformation
     */
    links?: Links;
    /**
     * 
     * @type {WarningsType}
     * @memberof MemberInformation
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the MemberInformation interface.
 */
export function instanceOfMemberInformation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MemberInformationFromJSON(json: any): MemberInformation {
    return MemberInformationFromJSONTyped(json, false);
}

export function MemberInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'memberInfo': !exists(json, 'memberInfo') ? undefined : MemberInfoRSTypeFromJSON(json['memberInfo']),
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function MemberInformationToJSON(value?: MemberInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'memberInfo': MemberInfoRSTypeToJSON(value.memberInfo),
        'links': LinksToJSON(value.links),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

