/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Cashiering API
 * APIs to cater for Cashiering related functionality in OPERA Cloud.<br /><br /> Cashiering provides access to a guest folio, posting journals, receipt histories, currency calculations, credit card settlements, and check a guest out.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { PostRateCodeCriteriaType } from './PostRateCodeCriteriaType';
import {
    PostRateCodeCriteriaTypeFromJSON,
    PostRateCodeCriteriaTypeFromJSONTyped,
    PostRateCodeCriteriaTypeToJSON,
} from './PostRateCodeCriteriaType';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * 
 * @export
 * @interface PostRateCodeRequest
 */
export interface PostRateCodeRequest {
    /**
     * 
     * @type {PostRateCodeCriteriaType}
     * @memberof PostRateCodeRequest
     */
    criteria?: PostRateCodeCriteriaType;
    /**
     * 
     * @type {Links}
     * @memberof PostRateCodeRequest
     */
    links?: Links;
    /**
     * 
     * @type {WarningsType}
     * @memberof PostRateCodeRequest
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the PostRateCodeRequest interface.
 */
export function instanceOfPostRateCodeRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostRateCodeRequestFromJSON(json: any): PostRateCodeRequest {
    return PostRateCodeRequestFromJSONTyped(json, false);
}

export function PostRateCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRateCodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'criteria': !exists(json, 'criteria') ? undefined : PostRateCodeCriteriaTypeFromJSON(json['criteria']),
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function PostRateCodeRequestToJSON(value?: PostRateCodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'criteria': PostRateCodeCriteriaTypeToJSON(value.criteria),
        'links': LinksToJSON(value.links),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

