/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Rate API
 * APIs to cater for Rate Availability functionality in OPERA Cloud. <br /><br /> Rate Management provides all the tools you need to effectively define and manage the rate structures for a property in OPERA Cloud. Some of the things you can do include creating and managing rate codes, rate classes, rate categories, display sets, rate strategies, as well as managing promotion groups and codes.<br /><br /> Compatible with OPERA Cloud release 21.5.0.0.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2022 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 21.5.0.0
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatePlanScheduleClassificationsType
 */
export interface RatePlanScheduleClassificationsType {
    /**
     * Market code for the rate schedule.
     * @type {string}
     * @memberof RatePlanScheduleClassificationsType
     */
    marketCode?: string;
    /**
     * Source code for the rate schedule.
     * @type {string}
     * @memberof RatePlanScheduleClassificationsType
     */
    sourceCode?: string;
}

/**
 * Check if a given object implements the RatePlanScheduleClassificationsType interface.
 */
export function instanceOfRatePlanScheduleClassificationsType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RatePlanScheduleClassificationsTypeFromJSON(json: any): RatePlanScheduleClassificationsType {
    return RatePlanScheduleClassificationsTypeFromJSONTyped(json, false);
}

export function RatePlanScheduleClassificationsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatePlanScheduleClassificationsType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'marketCode': !exists(json, 'marketCode') ? undefined : json['marketCode'],
        'sourceCode': !exists(json, 'sourceCode') ? undefined : json['sourceCode'],
    };
}

export function RatePlanScheduleClassificationsTypeToJSON(value?: RatePlanScheduleClassificationsType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'marketCode': value.marketCode,
        'sourceCode': value.sourceCode,
    };
}

