/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Event Configuration API
 * This API caters for Event Configuration in OPERA Cloud. <br /><There are operations to post, update, fetch and delete codes such as item inventory, function spaces, menu items and many more.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality-integrations_ww@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * It represents Menu as Resource.
 * @export
 */
export const EventResourceType = {
    Space: 'Space',
    Item: 'Item',
    Menu: 'Menu'
} as const;
export type EventResourceType = typeof EventResourceType[keyof typeof EventResourceType];


export function EventResourceTypeFromJSON(json: any): EventResourceType {
    return EventResourceTypeFromJSONTyped(json, false);
}

export function EventResourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventResourceType {
    return json as EventResourceType;
}

export function EventResourceTypeToJSON(value?: EventResourceType | null): any {
    return value as any;
}

