/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Event Configuration API
 * This API caters for Event Configuration in OPERA Cloud. <br /><There are operations to post, update, fetch and delete codes such as item inventory, function spaces, menu items and many more.<br /><br /> Compatible with OPERA Cloud release 23.2.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2023 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 23.2
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
} from './Links';
import type { RevenueGroupsType } from './RevenueGroupsType';
import {
    RevenueGroupsTypeFromJSON,
    RevenueGroupsTypeFromJSONTyped,
    RevenueGroupsTypeToJSON,
} from './RevenueGroupsType';
import type { WarningsType } from './WarningsType';
import {
    WarningsTypeFromJSON,
    WarningsTypeFromJSONTyped,
    WarningsTypeToJSON,
} from './WarningsType';

/**
 * Request object for changing existing Catering Revenue Groups Configurations.
 * @export
 * @interface RevenueGroups
 */
export interface RevenueGroups {
    /**
     * 
     * @type {Links}
     * @memberof RevenueGroups
     */
    links?: Links;
    /**
     * 
     * @type {RevenueGroupsType}
     * @memberof RevenueGroups
     */
    revenueGroups?: RevenueGroupsType;
    /**
     * 
     * @type {WarningsType}
     * @memberof RevenueGroups
     */
    warnings?: WarningsType;
}

/**
 * Check if a given object implements the RevenueGroups interface.
 */
export function instanceOfRevenueGroups(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RevenueGroupsFromJSON(json: any): RevenueGroups {
    return RevenueGroupsFromJSONTyped(json, false);
}

export function RevenueGroupsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevenueGroups {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : LinksFromJSON(json['links']),
        'revenueGroups': !exists(json, 'revenueGroups') ? undefined : RevenueGroupsTypeFromJSON(json['revenueGroups']),
        'warnings': !exists(json, 'warnings') ? undefined : WarningsTypeFromJSON(json['warnings']),
    };
}

export function RevenueGroupsToJSON(value?: RevenueGroups | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': LinksToJSON(value.links),
        'revenueGroups': RevenueGroupsTypeToJSON(value.revenueGroups),
        'warnings': WarningsTypeToJSON(value.warnings),
    };
}

