/*
OPERA Cloud Enterprise Configuration API

APIs to cater for Enterprise Configuration functionality in OPERA Cloud. <br /><br In this module, you can configure a variety of options related to your properties such as their locations, facilities, and local attractions. The available options are dependant on the active controls at your property.<br /><br /> Compatible with OPERA Cloud release 26.2.0.0.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2026 Oracle and/or its affiliates.</p>

API version: 26.2.0.0
Contact: hospitality_apis_ww_grp@oracle.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package entcfg

import (
	"encoding/json"
)

// checks if the IframeDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IframeDomain{}

// IframeDomain Details associated with the iframe domain.
type IframeDomain struct {
	// Domain Name to identify Iframe domain Url.
	DomainName *string `json:"domainName,omitempty"`
	// Domain Url which is to be supported by Iframes.
	DomainUrl *string `json:"domainUrl,omitempty"`
	// Indicates if the domain is approved.
	Approved *bool `json:"approved,omitempty"`
}

// NewIframeDomain instantiates a new IframeDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIframeDomain() *IframeDomain {
	this := IframeDomain{}
	return &this
}

// NewIframeDomainWithDefaults instantiates a new IframeDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIframeDomainWithDefaults() *IframeDomain {
	this := IframeDomain{}
	return &this
}

// GetDomainName returns the DomainName field value if set, zero value otherwise.
func (o *IframeDomain) GetDomainName() string {
	if o == nil || IsNil(o.DomainName) {
		var ret string
		return ret
	}
	return *o.DomainName
}

// GetDomainNameOk returns a tuple with the DomainName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IframeDomain) GetDomainNameOk() (*string, bool) {
	if o == nil || IsNil(o.DomainName) {
		return nil, false
	}
	return o.DomainName, true
}

// HasDomainName returns a boolean if a field has been set.
func (o *IframeDomain) HasDomainName() bool {
	if o != nil && !IsNil(o.DomainName) {
		return true
	}

	return false
}

// SetDomainName gets a reference to the given string and assigns it to the DomainName field.
func (o *IframeDomain) SetDomainName(v string) {
	o.DomainName = &v
}

// GetDomainUrl returns the DomainUrl field value if set, zero value otherwise.
func (o *IframeDomain) GetDomainUrl() string {
	if o == nil || IsNil(o.DomainUrl) {
		var ret string
		return ret
	}
	return *o.DomainUrl
}

// GetDomainUrlOk returns a tuple with the DomainUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IframeDomain) GetDomainUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DomainUrl) {
		return nil, false
	}
	return o.DomainUrl, true
}

// HasDomainUrl returns a boolean if a field has been set.
func (o *IframeDomain) HasDomainUrl() bool {
	if o != nil && !IsNil(o.DomainUrl) {
		return true
	}

	return false
}

// SetDomainUrl gets a reference to the given string and assigns it to the DomainUrl field.
func (o *IframeDomain) SetDomainUrl(v string) {
	o.DomainUrl = &v
}

// GetApproved returns the Approved field value if set, zero value otherwise.
func (o *IframeDomain) GetApproved() bool {
	if o == nil || IsNil(o.Approved) {
		var ret bool
		return ret
	}
	return *o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IframeDomain) GetApprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.Approved) {
		return nil, false
	}
	return o.Approved, true
}

// HasApproved returns a boolean if a field has been set.
func (o *IframeDomain) HasApproved() bool {
	if o != nil && !IsNil(o.Approved) {
		return true
	}

	return false
}

// SetApproved gets a reference to the given bool and assigns it to the Approved field.
func (o *IframeDomain) SetApproved(v bool) {
	o.Approved = &v
}

func (o IframeDomain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IframeDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DomainName) {
		toSerialize["domainName"] = o.DomainName
	}
	if !IsNil(o.DomainUrl) {
		toSerialize["domainUrl"] = o.DomainUrl
	}
	if !IsNil(o.Approved) {
		toSerialize["approved"] = o.Approved
	}
	return toSerialize, nil
}

type NullableIframeDomain struct {
	value *IframeDomain
	isSet bool
}

func (v NullableIframeDomain) Get() *IframeDomain {
	return v.value
}

func (v *NullableIframeDomain) Set(val *IframeDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableIframeDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableIframeDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIframeDomain(val *IframeDomain) *NullableIframeDomain {
	return &NullableIframeDomain{value: val, isSet: true}
}

func (v NullableIframeDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIframeDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


