/* tslint:disable */
/* eslint-disable */
/**
 * OPERA Cloud Reservation Asynchronous API
 * APIs to cater for Reservation Asynchronous functionality in OPERA Cloud. This includes viewing reservation data along with its revenue. <p>This API follows an async pattern where</p><ul><li>You make an initial request, which returns a Location header</li><li>You poll HEAD on the Location header returned to obtain the status of the process</li><li>Once the process completes HEAD will return in the Location header the URL that must be called to obtain the results of the process</li><li>You call the URL to obtain the results of the process</li></ul><br /><br /> Compatible with OPERA Cloud release 24.4.<br /><br /><p> This document and all content within is available under the Universal Permissive License v 1.0 (https://oss.oracle.com/licenses/upl). Copyright (c) 2020, 2024 Oracle and/or its affiliates.</p>
 *
 * The version of the OpenAPI document: 24.4
 * Contact: hospitality_apis_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Response object for outcome of validate rooming list reservations with Success or Fail status and Errors related to this operation.
 * @export
 * @interface ValidateRoomingListOutcomeType
 */
export interface ValidateRoomingListOutcomeType {
    /**
     * Unique Reservation Id
     * @type {number}
     * @memberof ValidateRoomingListOutcomeType
     */
    reservationId?: number;
    /**
     * Sequencial number of an individual reservation in rooming list.
     * @type {number}
     * @memberof ValidateRoomingListOutcomeType
     */
    reservationSeqNo?: number;
    /**
     * Guest's Full display name.
     * @type {string}
     * @memberof ValidateRoomingListOutcomeType
     */
    guestFullName?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidateRoomingListOutcomeType
     */
    roomType?: string;
    /**
     * Display the arrival date of the guest.
     * @type {string}
     * @memberof ValidateRoomingListOutcomeType
     */
    arrivalDate?: string;
    /**
     * Display the departure date of the guest.
     * @type {string}
     * @memberof ValidateRoomingListOutcomeType
     */
    departureDate?: string;
    /**
     * Validate Status.
     * @type {string}
     * @memberof ValidateRoomingListOutcomeType
     */
    validateStatus?: ValidateRoomingListOutcomeTypeValidateStatusEnum;
    /**
     * Status messages of validate rooming list
     * @type {object}
     * @memberof ValidateRoomingListOutcomeType
     */
    outcomeMessages?: object;
}


/**
 * @export
 */
export const ValidateRoomingListOutcomeTypeValidateStatusEnum = {
    Success: 'Success',
    Fail: 'Fail'
} as const;
export type ValidateRoomingListOutcomeTypeValidateStatusEnum = typeof ValidateRoomingListOutcomeTypeValidateStatusEnum[keyof typeof ValidateRoomingListOutcomeTypeValidateStatusEnum];


/**
 * Check if a given object implements the ValidateRoomingListOutcomeType interface.
 */
export function instanceOfValidateRoomingListOutcomeType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ValidateRoomingListOutcomeTypeFromJSON(json: any): ValidateRoomingListOutcomeType {
    return ValidateRoomingListOutcomeTypeFromJSONTyped(json, false);
}

export function ValidateRoomingListOutcomeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateRoomingListOutcomeType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reservationId': !exists(json, 'reservationId') ? undefined : json['reservationId'],
        'reservationSeqNo': !exists(json, 'reservationSeqNo') ? undefined : json['reservationSeqNo'],
        'guestFullName': !exists(json, 'guestFullName') ? undefined : json['guestFullName'],
        'roomType': !exists(json, 'roomType') ? undefined : json['roomType'],
        'arrivalDate': !exists(json, 'arrivalDate') ? undefined : json['arrivalDate'],
        'departureDate': !exists(json, 'departureDate') ? undefined : json['departureDate'],
        'validateStatus': !exists(json, 'validateStatus') ? undefined : json['validateStatus'],
        'outcomeMessages': !exists(json, 'outcomeMessages') ? undefined : json['outcomeMessages'],
    };
}

export function ValidateRoomingListOutcomeTypeToJSON(value?: ValidateRoomingListOutcomeType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reservationId': value.reservationId,
        'reservationSeqNo': value.reservationSeqNo,
        'guestFullName': value.guestFullName,
        'roomType': value.roomType,
        'arrivalDate': value.arrivalDate,
        'departureDate': value.departureDate,
        'validateStatus': value.validateStatus,
        'outcomeMessages': value.outcomeMessages,
    };
}

